### ISSUE TITLE
Implement Search operation for LInked List

### ISSUE THREAD

**Issue by ingoscardan** [ingoscardan/dotnet.AlgorithmsAndDatastructures.v1#2]
Implement Search operation of the Linked List Data structure.

### Task

- [x] Implement the method to search an element by Node
- [x] Implement the method to search an element by Value

### Acceptance Criteria
Implement below test cases. All test cases should pass.

- [x] Search a value on an empty Linked List. Should return null.
- [x] Search a node on an empty Linked List. Should return null.
- [x] Search an existing element by Value and by Node within the Linked List. Should return a Node.
